%% ATTENTION !!!! NO CLEARING OF DATA HERE AS WE USE DATA GENERATED BY 
%FULLLOADJOHANNES.M

nStack = 5;
E1K = [exist('S1_1K','var'), exist('S2_1K','var')];
n1K = sum(E1K);
E5K = [exist('S1_5K','var'), exist('S2_5K','var')];
n5K = sum(E5K);
n2Plot = sum(E1K +E5K); %count number of variable present

%% FullCDF picture 1K

%#1 Try without error bars
assert(~all(E1K==0),'No Data found for 1K')
figure()
hold on

for j = 1:nStack
    
    if E1K(1)
       p11(j) = plot(S1_1K.Table025(j).CCDF(:,1),S1_1K.Table025(j).CCDF(:,2),'g');
       p12(j) = plot(S1_1K.Table050(j).CCDF(:,1),S1_1K.Table050(j).CCDF(:,2),'b');
       p13(j) = plot(S1_1K.Table100(j).CCDF(:,1),S1_1K.Table100(j).CCDF(:,2),'r');
    end
        
    if E1K(2)
        p21(j) = plot(S2_1K.Table025(j).CCDF(:,1),S2_1K.Table025(j).CCDF(:,2),'--g');
        p22(j) = plot(S2_1K.Table050(j).CCDF(:,1),S2_1K.Table050(j).CCDF(:,2),'--b');
        p23(j) = plot(S2_1K.Table100(j).CCDF(:,1),S2_1K.Table100(j).CCDF(:,2),'--r');
    end

end

a = gca;
a.XScale = 'log';
a.YScale = 'log';
title('1K all samples all stacks')
xlabel('Pore Size (um^2)')
ylabel('CCDF [0 1]')
legend([p13(1) p23(1) p12(1) p11(1)],{'Sample1-1.00mg/mL','Sample2-1.00mg/mL','0.50mg/mL','0.25mg/mL'})
hold off

%In Linear Scale
figure()
hold on

for j = 1:nStack
    
    if E1K(1)
        plot(p11(j).XData,p11(j).YData,'g')
        plot(p12(j).XData,p12(j).YData,'b')
        plot(p13(j).XData,p13(j).YData,'r')
    end
        
    if E1K(2)
        plot(p21(j).XData,p21(j).YData,'--g')
        plot(p22(j).XData,p22(j).YData,'--b')
        plot(p23(j).XData,p23(j).YData,'--r')
    end

end

ylim([0 1])
xlim([0 50])
xlabel('Pore Size (um^2)')
ylabel('CCDF [0 1]')
title('1K all samples all stacks')
legend([p13(1) p23(1) p12(1) p11(1)],{'Sample1-1.00mg/mL','Sample2-1.00mg/mL','0.50mg/mL','0.25mg/mL'})
hold off

%clear p11 p12 p13 p21 p22 p23;
%% FullCDF picture 5K

%#1 Try without error bars
assert(~all(E5K==0),'No Data found for 1K')
figure()
hold on

for j = 1:nStack
    
    if E1K(1)
       p11(j) = plot(S1_5K.Table025(j).CCDF(:,1),S1_5K.Table025(j).CCDF(:,2),'g');
       p12(j) = plot(S1_5K.Table050(j).CCDF(:,1),S1_5K.Table050(j).CCDF(:,2),'b');
       p13(j) = plot(S1_5K.Table100(j).CCDF(:,1),S1_5K.Table100(j).CCDF(:,2),'r');
    end
        
    if E1K(2)
        p21(j) = plot(S2_5K.Table025(j).CCDF(:,1),S2_5K.Table025(j).CCDF(:,2),'--g');
        p22(j) = plot(S2_5K.Table050(j).CCDF(:,1),S2_5K.Table050(j).CCDF(:,2),'--b');
        p23(j) = plot(S2_5K.Table100(j).CCDF(:,1),S2_5K.Table100(j).CCDF(:,2),'--r');
    end

end

a = gca;
a.XScale = 'log';
a.YScale = 'log';
title('5K all samples all stacks')
xlabel('Pore Size (um^2)')
ylabel('CCDF [0 1]')
legend([p13(1) p23(1) p12(1) p11(1)],{'Sample1-1.00mg/mL','Sample2-1.00mg/mL','0.50mg/mL','0.25mg/mL'})
hold off

%In Linear Scale
figure()
hold on

for j = 1:nStack
    
    if E1K(1)
        plot(p11(j).XData,p11(j).YData,'g')
        plot(p12(j).XData,p12(j).YData,'b')
        plot(p13(j).XData,p13(j).YData,'r')
    end
        
    if E1K(2)
        plot(p21(j).XData,p21(j).YData,'--g')
        plot(p22(j).XData,p22(j).YData,'--b')
        plot(p23(j).XData,p23(j).YData,'--r')
    end

end

ylim([0 1])
xlim([0 50])
xlabel('Pore Size (um^2)')
ylabel('CCDF [0 1]')
title('5K all samples all stacks')
legend([p13(1) p23(1) p12(1) p11(1)],{'Sample1-1.00mg/mL','Sample2-1.00mg/mL','0.50mg/mL','0.25mg/mL'})
hold off

clear p11 p12 p13 p21 p22 p23;

%% 1K Average of Both Samples
nBins = 50;

if all(E1K==1)
figure()

hold on
name = fieldnames(S1_1K);
numField = length(name);
color = ['-g';'-b';'-r'];

for i = 1 : numField
    
    totData = [S1_1K.(name{i})(1).allCCDF; S2_1K.(name{i})(1).allCCDF];
    [x,ind] = sort(totData(:,1));
    [midBin, Freq, LFreq] = Plotting.lnbin(x,nBins);
    y = totData(ind,2);
    meanSamples = zeros(1,length(midBin));
    stdSamples = zeros(1,length(midBin));
    for j = 1 : length(midBin)-1
        meanSamples(j) = nanmean(y(and(x<=midBin(j+1),x>midBin(j))));
        stdSamples(j)  = nanstd(y(and(x<=midBin(j+1),x>midBin(j))));
    end
    %clean data
    midBin(isnan(meanSamples))=[];
    stdSamples(isnan(meanSamples)) = [];
    meanSamples((isnan(meanSamples))) =[];
    p1K(i) = Plotting.shadedErrorBar(midBin(:),meanSamples(:),stdSamples(:),'lineProps',color(i,:),'logScale',true);
    
end
hold off
a = gca;
ylim([1e-6 1]);
a.XScale = 'log';
a.YScale = 'log';
xlabel('Pore Size (um^2)')
ylabel('CCDF [0 1]')
legend([p1K(3).mainLine p1K(2).mainLine p1K(1).mainLine],{'1.00mg/mL','0.50mg/mL','0.25mg/mL'})
title('Average of both samples for 1K with lines representing standard deviation')
clear p1K;
end

%% 5K average of Both sample

nBins = 50;

if all(E1K==1)
figure()

hold on
name = fieldnames(S1_5K);
numField = length(name);
color = ['-g';'-b';'-r'];

for i = 1 : numField
    
    totData = [S1_5K.(name{i})(1).allCCDF; S2_5K.(name{i})(1).allCCDF];
    [x,ind] = sort(totData(:,1));
    [midBin, Freq, LFreq] = Plotting.lnbin(x,nBins);
    y = totData(ind,2);
    meanSamples = zeros(1,length(midBin));
    stdSamples = zeros(1,length(midBin));
    for j = 1 : length(midBin)-1
        meanSamples(j) = nanmean(y(and(x<=midBin(j+1),x>midBin(j))));
        stdSamples(j)  = nanstd(y(and(x<=midBin(j+1),x>midBin(j))));
    end
    %clean data
    midBin(isnan(meanSamples))=[];
    stdSamples(isnan(meanSamples)) = [];
    meanSamples((isnan(meanSamples))) =[];
    p5K(i) = Plotting.shadedErrorBar(midBin(:),meanSamples(:),stdSamples(:),'lineProps',color(i,:),'logScale',true);
    
end
hold off
a = gca;
a.XScale = 'log';
a.YScale = 'log';
xlabel('Pore Size (um^2)')
ylabel('CCDF [0 1]')
legend([p5K(3).mainLine p5K(2).mainLine p5K(1).mainLine],{'1.00mg/mL','0.50mg/mL','0.25mg/mL'})
title('Average of both samples for 5K with lines representing standard deviation')
clear p5K;
end

%% Comparing 1K and 5K

if all(E1K==1)
figure()

hold on
%1K
name = fieldnames(S1_5K);
numField = length(name);
color = ['-g';'-b';'-r'];

for i = 1 : numField
    
    totData = [S1_1K.(name{i})(1).allCCDF; S2_1K.(name{i})(1).allCCDF];
    [x,ind] = sort(totData(:,1));
    [midBin, Freq, LFreq] = Plotting.lnbin(x,nBins);
    y = totData(ind,2);
    meanSamples = zeros(1,length(midBin));
    stdSamples = zeros(1,length(midBin));
    for j = 1 : length(midBin)-1
        meanSamples(j) = nanmean(y(and(x<=midBin(j+1),x>midBin(j))));
        stdSamples(j)  = nanstd(y(and(x<=midBin(j+1),x>midBin(j))));
    end
    %clean data
    midBin(isnan(meanSamples))=[];
    stdSamples(isnan(meanSamples)) = [];
    meanSamples((isnan(meanSamples))) =[];
    p1K(i) = Plotting.shadedErrorBar(midBin(:),meanSamples(:),stdSamples(:),'lineProps',color(i,:),'logScale',true);
    
end

name = fieldnames(S1_5K);
numField = length(name);
color = ['--g';'--b';'--r'];

for i = 1 : numField
    
    totData = [S1_5K.(name{i})(1).allCCDF; S2_5K.(name{i})(1).allCCDF];
    [x,ind] = sort(totData(:,1));
    [midBin, Freq, LFreq] = Plotting.lnbin(x,nBins);
    y = totData(ind,2);
    meanSamples = zeros(1,length(midBin));
    stdSamples = zeros(1,length(midBin));
    for j = 1 : length(midBin)-1
        meanSamples(j) = nanmean(y(and(x<=midBin(j+1),x>midBin(j))));
        stdSamples(j)  = nanstd(y(and(x<=midBin(j+1),x>midBin(j))));
    end
    %clean data
    midBin(isnan(meanSamples))=[];
    stdSamples(isnan(meanSamples)) = [];
    meanSamples((isnan(meanSamples))) =[];
    p5K(i) = Plotting.shadedErrorBar(midBin(:),meanSamples(:),stdSamples(:),'lineProps',color(i,:),'logScale',true);
    
end

hold off
a = gca;
a.XScale = 'log';
a.YScale = 'log';
xlabel('Pore Size (um^2)')
ylabel('CCDF [0 1]')

title('Comparison of 1K and 5K for 3 different concentration')

legend([p1K(3).mainLine,p1K(2).mainLine,p1K(1).mainLine,p5K(3).mainLine p5K(2).mainLine,p5K(1).mainLine],...
    {'1K - 1.00mg/mL', '1k - 0.50mg/mL','1k - 0.25mg/mL', '5K - 1.00mg/mL', '5k - 0.50mg/mL','5k - 0.25mg/mL'});

end


